[[extensions]]
name = "Customer Insight — Optimize Product"
handle = "customer-insight-product-link"
uid = "a5a11f2c-1a3e-a9e3-6823-40c8eec14b8e52e31ccb"
type = "admin_link"

[[extensions.targeting]]
target = "admin.product-details.action.link"
url = "/app/products/{id}/optimize"
