// Shared merchant-facing UI kit (Polaris + inline SVG, no chart library).
export * from "./format";
export { ScoreGauge } from "./ScoreGauge";
export type { ScoreGaugeProps } from "./ScoreGauge";
export { TrendIndicator } from "./TrendIndicator";
export type { TrendIndicatorProps } from "./TrendIndicator";
export { PriorityBadge } from "./PriorityBadge";
export type { PriorityBadgeProps, PriorityLevel } from "./PriorityBadge";
export { MetricCard } from "./MetricCard";
export type { MetricCardProps } from "./MetricCard";
export { BarChart } from "./BarChart";
export type { BarChartProps, BarDatum } from "./BarChart";
export { TrendChart } from "./TrendChart";
export type { TrendChartProps, TrendChartPoint } from "./TrendChart";
export { Sparkline } from "./Sparkline";
export type { SparklineProps } from "./Sparkline";
export { StickyActionBar } from "./StickyActionBar";
export type { StickyActionBarProps } from "./StickyActionBar";
export { SectionHeader } from "./SectionHeader";
export type { SectionHeaderProps } from "./SectionHeader";
export { OnboardingChecklist } from "./OnboardingChecklist";
export type { OnboardingChecklistProps, OnboardingStep } from "./OnboardingChecklist";
export { EmptyInsight } from "./EmptyInsight";
export type { EmptyInsightProps } from "./EmptyInsight";
export { DashboardSkeleton, ListSkeleton, DetailSkeleton } from "./Skeletons";
export { AppShell } from "./AppShell";
export { AppPage } from "./AppPage";
export { PageHeader } from "./PageHeader";
export { KpiCard } from "./KpiCard";
export { HeroRevenueCard } from "./HeroRevenueCard";
export { ActionCard } from "./ActionCard";
export { InsightOpportunityCard } from "./InsightOpportunityCard";
export { ProductRecoveryCard } from "./ProductRecoveryCard";
export { CompetitorCard } from "./CompetitorCard";
export { EmptyStateCard } from "./EmptyStateCard";
export { ChartCard } from "./ChartCard";
export { SeverityBadge } from "./SeverityBadge";
export { MetricBadge } from "./MetricBadge";
