import { describe, expect, it } from "vitest";

import { parseImport, sanitizeImportSource, VALID_IMPORT_SOURCES } from "~/lib/import";
import { runAnalysis } from "~/lib/engine";

describe("import source sanitization", () => {
  it("preserves valid sources unchanged", () => {
    for (const source of VALID_IMPORT_SOURCES) {
      expect(sanitizeImportSource(source)).toBe(source);
    }
  });

  it("falls back to manual for invalid source", () => {
    expect(sanitizeImportSource("unknown")).toBe("manual");
    expect(sanitizeImportSource("")).toBe("manual");
  });

  it("rejects product_text from user import", () => {
    expect(sanitizeImportSource("product_text")).toBe("manual");
  });

  it("rejects product_tags from user import", () => {
    expect(sanitizeImportSource("product_tags")).toBe("manual");
  });

  it("rejects order_tags from user import form (sync-only source)", () => {
    // order_tags is generated by sync, not accepted as a user-supplied source
    expect(sanitizeImportSource("order_tags")).toBe("manual");
  });
});

describe("parseImport stores correct source", () => {
  const now = new Date("2026-06-01T00:00:00Z");

  it("plain text import stores source=manual by default", () => {
    const result = parseImport("Do you offer free shipping?", { now });
    expect(result).toHaveLength(1);
    expect(result[0]?.source).toBe("manual");
  });

  it("manual source is preserved when passed", () => {
    const result = parseImport("Can I pay with PayPal?", { source: "manual", now });
    expect(result[0]?.source).toBe("manual");
  });

  it("csv source is preserved when passed", () => {
    const result = parseImport("content\nDo you offer returns?", { source: "csv", now });
    expect(result[0]?.source).toBe("csv");
  });

  it("cannot produce product_text source via parseImport", () => {
    const result = parseImport("some message", { source: "product_text", now });
    // parseImport trusts caller — the caller (action) must sanitize first
    // this test documents that the action's sanitizeImportSource call is the gate
    expect(sanitizeImportSource("product_text")).toBe("manual");
    // if sanitized source is passed, result has manual
    const safeResult = parseImport("some message", { source: sanitizeImportSource("product_text"), now });
    expect(safeResult[0]?.source).toBe("manual");
  });
});

describe("runAnalysis source eligibility", () => {
  const now = new Date("2026-06-01T00:00:00Z");

  it("includes manual messages in keyword analysis", () => {
    const result = runAnalysis({
      now,
      messages: [
        { id: "m1", content: "How long does shipping take?", source: "manual", occurredAt: now },
        { id: "m2", content: "Can I pay with PayPal?", source: "manual", occurredAt: now },
      ],
      products: [],
    });
    expect(result.messageCount).toBe(2);
    expect(result.keywordGroups.length).toBeGreaterThan(0);
    expect(result.storewideOpportunities.length).toBeGreaterThan(0);
  });

  it("excludes product_text messages from analysis", () => {
    const result = runAnalysis({
      now,
      messages: [
        {
          id: "p1",
          content: "Product title. Product tags: shipping, payment, return",
          source: "product_text",
          occurredAt: now,
        },
      ],
      products: [],
    });
    // product_text messages are stripped — no eligible messages, no opportunities
    expect(result.messageCount).toBe(0);
    expect(result.keywordGroups.length).toBe(0);
    expect(result.storewideOpportunities.length).toBe(0);
  });

  it("excludes product_tags messages from analysis", () => {
    const result = runAnalysis({
      now,
      messages: [
        {
          id: "pt1",
          content: "Product tags for Hoodie: shipping, returns, payment",
          source: "product_tags",
          occurredAt: now,
        },
      ],
      products: [],
    });
    expect(result.messageCount).toBe(0);
    expect(result.keywordGroups.length).toBe(0);
    expect(result.storewideOpportunities.length).toBe(0);
  });

  it("analyzes customer messages alongside catalog entries correctly", () => {
    const result = runAnalysis({
      now,
      messages: [
        // Catalog entries — must be ignored
        { id: "p1", content: "Product tags: shipping payment return", source: "product_text", occurredAt: now },
        { id: "p2", content: "Product tags for Hoodie: shipping", source: "product_tags", occurredAt: now },
        // Real customer questions — must be analyzed
        { id: "m1", content: "How long does shipping take?", source: "manual", occurredAt: now },
        { id: "m2", content: "Can I pay with PayPal or Klarna?", source: "chat", occurredAt: now },
        { id: "m3", content: "What is the return policy?", source: "email", occurredAt: now },
      ],
      products: [],
    });
    // Only 3 customer messages count
    expect(result.messageCount).toBe(3);
    expect(result.storewideOpportunities.map((o) => o.code)).toEqual(
      expect.arrayContaining(["STOREWIDE_SHIPPING_GAP", "STOREWIDE_PAYMENT_GAP", "STOREWIDE_RETURN_GAP"]),
    );
  });
});
