import type { KeywordGroup, KeywordGroupId } from "~/lib/types";

// The canonical friction keyword dictionary. Terms are lowercase. The engine
// matches on word/phrase boundaries after normalization, so keep terms short
// and unambiguous. frictionWeight (0..1) scales a group's contribution to the
// Insight Score and product confusion. leakageRisk flags groups whose sharp
// rise indicates lost revenue (returns, refunds, shipping, stock, payment).
export const KEYWORD_GROUPS: KeywordGroup[] = [
  {
    id: "shipping",
    label: "Shipping",
    question: "How much is shipping and where do you ship?",
    terms: [
      "shipping",
      "ship to",
      "shipping cost",
      "shipping fee",
      "free shipping",
      "international shipping",
      "customs",
      "duties",
      "courier",
      "tracking number",
    ],
    frictionWeight: 0.8,
    leakageRisk: true,
  },
  {
    id: "delivery",
    label: "Delivery time",
    question: "When will my order arrive?",
    terms: [
      "delivery",
      "deliver",
      "how long",
      "how many days",
      "arrive",
      "arrival",
      "eta",
      "lead time",
      "dispatch",
      "delayed",
      "late",
      "still waiting",
    ],
    frictionWeight: 0.75,
    leakageRisk: true,
  },
  {
    id: "return",
    label: "Returns",
    question: "What is your return policy?",
    terms: [
      "return",
      "returns",
      "send back",
      "return policy",
      "rma",
      "exchange",
      "wrong item",
      "doesn't fit",
      "does not fit",
    ],
    frictionWeight: 0.9,
    leakageRisk: true,
  },
  {
    id: "refund",
    label: "Refunds",
    question: "How do I get a refund?",
    terms: [
      "refund",
      "refunded",
      "money back",
      "chargeback",
      "reimburse",
      "cancel order",
      "cancel my order",
    ],
    frictionWeight: 0.95,
    leakageRisk: true,
  },
  {
    id: "size",
    label: "Size & fit",
    question: "What size should I choose?",
    terms: [
      "size",
      "sizing",
      "fit",
      "too small",
      "too big",
      "too large",
      "measurement",
      "measurements",
      "dimensions",
      "size chart",
      "true to size",
    ],
    frictionWeight: 0.7,
    leakageRisk: false,
  },
  {
    id: "ingredient",
    label: "Ingredients",
    question: "What is it made of / what are the ingredients?",
    terms: [
      "ingredient",
      "ingredients",
      "made of",
      "material",
      "materials",
      "contains",
      "allergen",
      "allergens",
      "gluten",
      "vegan",
      "sugar",
      "formula",
    ],
    frictionWeight: 0.6,
    leakageRisk: false,
  },
  {
    id: "origin",
    label: "Origin",
    question: "Where is this made / where does it come from?",
    terms: [
      "made in",
      "country of origin",
      "origin",
      "where is it from",
      "where does it come from",
      "imported",
      "locally made",
      "sourced",
    ],
    frictionWeight: 0.5,
    leakageRisk: false,
  },
  {
    id: "stock",
    label: "Stock & availability",
    question: "Is this in stock / when will it be back?",
    terms: [
      "in stock",
      "out of stock",
      "sold out",
      "back in stock",
      "restock",
      "availability",
      "available",
      "preorder",
      "pre-order",
      "waitlist",
    ],
    frictionWeight: 0.85,
    leakageRisk: true,
  },
  {
    id: "discount",
    label: "Discounts",
    question: "Do you have a discount or promo code?",
    terms: [
      "discount",
      "promo code",
      "coupon",
      "coupon code",
      "voucher",
      "sale",
      "deal",
      "cheaper",
      "price match",
      "student discount",
    ],
    frictionWeight: 0.55,
    leakageRisk: false,
  },
  {
    id: "warranty",
    label: "Warranty",
    question: "Is there a warranty or guarantee?",
    terms: [
      "warranty",
      "guarantee",
      "guaranteed",
      "broken",
      "defective",
      "faulty",
      "damaged",
      "repair",
      "replacement",
    ],
    frictionWeight: 0.7,
    leakageRisk: false,
  },
  {
    id: "payment",
    label: "Payment",
    question: "What payment methods do you accept?",
    terms: [
      "payment",
      "pay with",
      "credit card",
      "paypal",
      "installment",
      "installments",
      "afterpay",
      "klarna",
      "cod",
      "cash on delivery",
      "payment failed",
      "checkout error",
    ],
    frictionWeight: 0.8,
    leakageRisk: true,
  },
  {
    id: "certificate",
    label: "Certificates",
    question: "Is it certified / does it have certification?",
    terms: [
      "certificate",
      "certification",
      "certified",
      "fda",
      "ce mark",
      "iso",
      "organic certified",
      "lab tested",
      "authenticity",
      "genuine",
    ],
    frictionWeight: 0.5,
    leakageRisk: false,
  },
  {
    id: "caffeine",
    label: "Caffeine / content",
    question: "How much caffeine / active content does it have?",
    terms: [
      "caffeine",
      "caffeinated",
      "decaf",
      "mg of caffeine",
      "how strong",
      "potency",
      "dosage",
      "concentration",
    ],
    frictionWeight: 0.45,
    leakageRisk: false,
  },
  {
    id: "usage",
    label: "How to use",
    question: "How do I use this product?",
    terms: [
      "how to use",
      "how do i use",
      "instructions",
      "directions",
      "how often",
      "how much should i",
      "setup",
      "set up",
      "manual",
      "wash",
      "care",
    ],
    frictionWeight: 0.6,
    leakageRisk: false,
  },
  {
    id: "compare",
    label: "Comparison",
    question: "How does this compare to other options?",
    terms: [
      "compare",
      "comparison",
      "difference between",
      "vs",
      "versus",
      "which is better",
      "better than",
      "alternative",
    ],
    frictionWeight: 0.65,
    leakageRisk: false,
  },
  {
    id: "competitor",
    label: "Competitor mention",
    question: "Are customers comparing you to competitors?",
    // Generic competitor-comparison cues. Brand names are matched separately
    // via DEFAULT_COMPETITOR_TERMS (and a per-shop override in settings).
    terms: [
      "competitor",
      "other brand",
      "another brand",
      "cheaper elsewhere",
      "found it cheaper",
      "amazon has",
      "same as",
    ],
    frictionWeight: 0.7,
    leakageRisk: false,
  },
];

/** Fast lookup by group id. */
export const KEYWORD_GROUPS_BY_ID: Record<KeywordGroupId, KeywordGroup> =
  KEYWORD_GROUPS.reduce(
    (acc, group) => {
      acc[group.id] = group;
      return acc;
    },
    {} as Record<KeywordGroupId, KeywordGroup>,
  );

/**
 * Default competitor brand/marketplace names used by the competitor detector.
 * Merchants can extend this via the "competitorTerms" app setting. These are
 * matched as whole words (case-insensitive) against normalized message text.
 */
export const DEFAULT_COMPETITOR_TERMS: string[] = [
  "amazon",
  "ebay",
  "walmart",
  "aliexpress",
  "etsy",
  "temu",
  "shein",
  "target",
  "alibaba",
];

/** Groups whose sharp rise the revenue-leakage detector watches. */
export const LEAKAGE_GROUP_IDS: KeywordGroupId[] = KEYWORD_GROUPS.filter(
  (group) => group.leakageRisk,
).map((group) => group.id);
